NeivaNet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('posts.urls')),
    path('', include('notifications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("posts/", views.posts, name="posts"),
    path("delete_post/<int:post_id>/", views.delete_post, name="delete_post"),
    path("delete_comment/<int:comment_id>/", views.delete_comment, name="delete_comment"),
    path("delete_reply/<int:reply_id>/", views.delete_reply, name="delete_reply"),
    path('toggle_like/<int:post_id>/', views.toggle_like, name='toggle_like'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('edit_comment/', views.edit_comment, name='edit_comment'),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def average_ranking(self):
        posts = Post.objects.filter(category=self)
        total_ranking = sum([post.ranking for post in posts if post.ranking is not None])
        count = posts.filter(ranking__isnull=False).count()
        return total_ranking / count if count > 0 else 0

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    date_posted = models.DateTimeField(auto_now_add=True)
    ranking = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)], 
        null=True, 
        blank=True
    )

    def __str__(self):
        return self.title
    
    def has_user_liked(self, user):
        return self.likes.filter(user=user).exists()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')

    def __str__(self):
        return f"Comment by {self.user} on {self.post.title}"
    
    def get_all_replies(self):
        replies = list(self.replies.all())
        for reply in self.replies.all():
            replies.extend(reply.get_all_replies())
        return replies

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="likes")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_liked = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['post', 'user']

class PostImage(models.Model):
    post = models.ForeignKey(Post, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_images/')

    def __str__(self):
        return f"Image for {self.post.title}"

posts/forms.py
from django import forms
from .models import Category, Post, Comment

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class PostForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=True,
        label='Categoría'
    )
    images = MultipleFileField(required=False)
    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'images']
        labels = {
            'title': 'Título',
            'content': 'Contenido',
            'images': 'Imagenes',
        }

class CommentForm(forms.ModelForm):
    parent_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Comment
        fields = ['content', 'parent_id']

posts/views.py
from django.shortcuts import redirect, render
from posts.models import Post, Like
from .forms import PostForm, CommentForm
from django.http import JsonResponse
from django.db.models import Prefetch
from .models import Comment, Post, PostImage
from django.db.models import Func, IntegerField
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

class Round(Func):
    function = 'ROUND'
    template = '%(function)s(%(expressions)s, 0)'

    def __init__(self, expression):
        super().__init__(expression, output_field=IntegerField())

@login_required
def posts(request):
    category_query = request.GET.get('category')
    context = {'category_query': category_query}
    
    # Inicializar form y comment_form al principio
    form = PostForm()
    comment_form = CommentForm()

    if request.method == 'POST':
        if "submit_post" in request.POST:
            form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.ranking = int(request.POST.get('ranking', 0)) if request.POST.get('ranking', 0).isdigit() else 0
                post.save()
                # Guardar las imágenes
                for file in request.FILES.getlist('images'):
                    PostImage.objects.create(post=post, image=file)
                return redirect('posts')
        elif "submit_comment" in request.POST:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.user = request.user
                comment.post = Post.objects.get(id=request.POST.get("post_id"))
                parent_id = request.POST.get('parent_id')
                if parent_id:
                    comment.parent = Comment.objects.get(id=parent_id)
                comment.save()
                return redirect('posts')

    else:
        form = PostForm()
        comment_form = CommentForm()
    
    # Prepares posts with likes and star ratings for the template
    likes_prefetch = Prefetch('likes', queryset=Like.objects.filter(user=request.user), to_attr='current_user_like')
    all_posts = Post.objects.prefetch_related(likes_prefetch).order_by('-date_posted')
    if category_query:
        all_posts = all_posts.filter(category__name__icontains=category_query)

    for post in all_posts:
        post.is_liked = bool(post.current_user_like)
        post.star_ratings = get_star_ratings(post.ranking)
        post.top_level_comments = post.comments.filter(parent=None)

    context.update({
        'posts': all_posts,
        'form': form,
        'comment_form': comment_form,
    })

    return render(request, 'posts.html', context)

def toggle_like(request, post_id):
    post = Post.objects.get(pk=post_id)
    like, created = Like.objects.get_or_create(post=post, user=request.user)
    if not created:
        like.delete()
        is_liked = False
    else:
        is_liked = True

    return JsonResponse({"is_liked": is_liked, "likes_count": post.likes.count()})

def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    # Asegúrate de que el usuario actual sea el autor de la publicación
    if request.user == post.author:
        post.delete()

    return redirect('posts')

def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    # Asegúrate de que el usuario actual sea el autor del comentario o de la publicación
    if request.user == comment.user or request.user == comment.post.author:
        comment.delete()

    return redirect('posts')

def delete_reply(request, reply_id):
    reply = get_object_or_404(Comment, id=reply_id)

    # Asegúrate de que el usuario actual sea el autor de la respuesta o del comentario original o de la publicación        
    if request.user == reply.user or request.user == reply.parent.user or request.user == reply.post.author:
        reply.delete()
    
    return redirect('posts')

def get_star_ratings(rating):
    # Esta función devuelve una lista de estrellas según el rating
    stars = []
    # Asegúrate de que el rating no sea None antes de hacer la comparación
    if rating is None:
        rating = 0  # O cualquier lógica que decidas para manejar un rating no establecido
    for i in range(1, 6):
        if rating >= i:
            stars.append('full')
        elif rating >= i - 0.5:
            stars.append('half')
        else:
            stars.append('empty')
    return stars

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.ranking = int(request.POST.get('ranking', 0)) if request.POST.get('ranking', 0).isdigit() else 0
                post.save()
                return redirect('posts')
    else:
        form = PostForm(instance=post)
    return render(request, 'edit_post.html', {'form': form})

@login_required
def edit_comment(request):
    # Verificar si la solicitud es AJAX
    if request.method == 'POST' and request.accepts("application/json"):
        comment_id = request.POST.get('comment_id')
        new_content = request.POST.get('content')

        comment = get_object_or_404(Comment, id=comment_id, user=request.user)
        comment.content = new_content
        comment.save()

        return JsonResponse({'message': 'Comentario actualizado correctamente.'})

    return JsonResponse({'message': 'Solicitud inválida.'}, status=400)

posts/templates/_post_form.html
{% load static %}

<div class="publish">
    <div class="row_title">
        <span><i class="fa-regular fa-newspaper"></i> {{ form_title }}</span>
    </div>
    <form method="post" enctype="multipart/form-data" id="postForm">
        <div class="publish_textarea">
            {% if user.userprofile and user.userprofile.profile_picture and user.userprofile.profile_picture.url != 'default.png' %}
                <img class="mini_profile_pic border-radius-image" src="{{ user.userprofile.profile_picture.url }}" onerror="this.onerror=null;this.src='{% static 'default.png' %}';" alt="{{ user.username }}" width="200">
            {% else %}
                <img class="mini_profile_pic border-radius-image" src="{% static 'default.png' %}" alt="Default Profile Pic" width="200">
            {% endif %}
            <div class="publish-content">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != "images" %}
                        <div class="formulario-posts">
                            {{ field.label_tag }}
                            {{ field }}
                            
                            {% if field.errors %}
                                <div class="error">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
                <div>Califica el servicio público recibido:</div>
                <div class="star-rating" style="margin:1% 0 0 1%">
                    {% for i in "12345" %}
                    <span class="fa-regular fa-star" style="color:#ffcd02; margin-left:-1%;" data-value="{{forloop.counter}}"></span>
                    {% endfor %}
                    <input type="hidden" name="ranking" id="id_ranking" required>
                </div>
                <div id="rankingError" class="error-message" style="display: none; margin-top:1em;">
                    Por favor, califica el servicio público recibido antes de publicar.
                </div>
                <div id="image-previews" style="display: flex; flex-wrap: wrap; gap: 10px;">
            
                </div>
            </div>

        </div>
        
        <div class="publish_icons">
            <ul>
                <li>
                    <label for="id_images" style="cursor: pointer;">
                        <i class="fa fa-camera"></i>
                    </label>
                    <input type="file" name="images" id="id_images" multiple style="display: none;" accept="image/*">
                </li>   
                <button type="submit" name="submit_post">Publicar</button>                     
            </ul>
        </div>                
    </form>
</div>

posts/templates/edit_post.html
{% extends "base.html" %}
{% block content %}
<div class="right_row">
    <div class="row">
        {% include '_post_form.html' with form=form form_title="Editar Publicación" %}
    </div>
</div>
<script>
    document.getElementById('id_images').addEventListener('change', function(event) {
        var imageContainer = document.getElementById('image-previews');
        imageContainer.innerHTML = ''; // Limpiar vistas previas anteriores

        Array.from(event.target.files).forEach(file => {
            var reader = new FileReader();
            reader.onload = function(e) {
                var img = document.createElement('img');
                img.src = e.target.result;
                img.style.maxWidth = '150px';
                img.style.height = 'auto';
                imageContainer.appendChild(img);
            };
            reader.readAsDataURL(file);
        });

        imageContainer.style.display = event.target.files.length ? 'flex' : 'none';
    });

    document.addEventListener('input', function (e) {
        if (e.target.tagName.toLowerCase() === 'textarea' && e.target.classList.contains('autoExpand')) {
            e.target.style.height = 'auto';
            e.target.style.height = e.target.scrollHeight + 'px';
        }
    }, false);    

    //manejo de likes
    document.addEventListener("DOMContentLoaded", function() {
        const likeLinks = document.querySelectorAll(".like-link");
        likeLinks.forEach(link => {
            link.addEventListener("click", function(e) {
                e.preventDefault();
                const postID = e.currentTarget.dataset.postid;
                fetch(`/toggle_like/${postID}/`)
                    .then(response => response.json())
                    .then(data => {
                        const likesCount = data.likes_count;
                        const isLiked = data.is_liked; // Esta variable indica si el usuario actual dio "like".
                        const heartElement = link.querySelector(".fa-heart");
                        const likeCountElement = link.querySelector(".like-count");
    
                        // Actualizamos el número de "likes".
                        likeCountElement.textContent = likesCount;
    
                        // Cambiamos el color del corazón según si el usuario actual ha dado "like".
                        if (isLiked) {
                            heartElement.style.color = "#f0566a";
                            likeCountElement.style.color = "#f0566a";
                            heartElement.classList.add("selected-orange");
                        } else {
                            heartElement.style.color = "#246da2";
                            likeCountElement.style.color = "#246da2";
                            heartElement.classList.remove("selected-orange");
                        }
                    });
            });
        });
    });

    //manejo de estrellas
    document.addEventListener('DOMContentLoaded', function() {
        let stars = document.querySelectorAll('.star-rating .fa-regular');
        let currentRating = 0; // Mantendrá la puntuación actual seleccionada
    
        function updateStars(rating) {
            stars.forEach(function(star, index) {
                if (index < rating) {
                    star.classList.remove('fa-regular');
                    star.classList.add('fa-solid');
                } else {
                    star.classList.add('fa-regular');
                    star.classList.remove('fa-solid');
                }
            });
        }
    
        stars.forEach(function(star, index) {
            star.addEventListener('click', function() {
                currentRating = index + 1; // Establece la calificación actual
                document.getElementById('id_ranking').value = currentRating; // Actualiza el campo oculto
                updateStars(currentRating); // Actualiza las estrellas
            });
            star.addEventListener('mouseover', function() {
                updateStars(index + 1); // Actualiza las estrellas mientras se pasa por encima
            });
            star.addEventListener('mouseout', function() {
                updateStars(currentRating); // Restaura la calificación actual cuando el ratón sale
            });
        });
    });
    
    //manejo de comentarios
    document.addEventListener("DOMContentLoaded", function() {
        const replyLinks = document.querySelectorAll(".reply-link");
        replyLinks.forEach(link => {
            link.addEventListener("click", function(e) {
                e.preventDefault();
                const replyFormId = e.target.getAttribute('href');
                const replyForm = document.querySelector(replyFormId);
                replyForm.style.display = replyForm.style.display === 'none' ? 'block' : 'none';
            });
        });
    });

    //manejo de envio de formulario de post
    document.getElementById('postForm').addEventListener('submit', function(e) {
        var rankingValue = document.getElementById('id_ranking').value;
        var errorDiv = document.getElementById('rankingError');
    
        if (!rankingValue) {
            e.preventDefault(); // Evita que el formulario se envíe
            errorDiv.style.display = 'block'; // Muestra el mensaje de error
        } else {
            errorDiv.style.display = 'none'; // Oculta el mensaje de error si está todo bien
        }
    });

    //edicion comentarios
    function showEditForm(commentId) {
        var editForm = document.getElementById('editForm' + commentId);
        editForm.style.display = 'block';
    }
    
    function submitEdit(commentId) {
        var newContent = document.getElementById('editContent' + commentId).value;
    
        fetch("{% url 'edit_comment' %}", {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: 'comment_id=' + commentId + '&content=' + encodeURIComponent(newContent)
        })
        .then(response => response.json())
        .then(data => {
            // Actualizar la interfaz de usuario con el nuevo contenido del comentario
            var commentTextElement = document.getElementById('commentText' + commentId);
            if (commentTextElement) {
                commentTextElement.textContent = newContent;
            }
            document.getElementById('editForm' + commentId).style.display = 'none';
        })
        .catch(error => console.error('Error:', error));
    }
    
    
</script>
{% endblock %}