NeivaNet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('posts.urls')),
    path('', include('notifications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from .views import RegisterView, UserProfileView, CustomPasswordResetView, update_profile, CustomLoginView
from accounts import views

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("", CustomLoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("profile/<int:user_id>/", UserProfileView.as_view(), name="profile"),
    path("update_profile/", update_profile, name="update_profile"),
    path("logout/", LogoutView.as_view(next_page='/'), name="logout"),
    path(
    "password_reset/<str:from_where>/",
    CustomPasswordResetView.as_view(),
    name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path('confirm_email/<uuid:token>/', views.confirm_email, name='confirm_email'),
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("posts/", views.posts, name="posts"),
    path("delete_post/<int:post_id>/", views.delete_post, name="delete_post"),
    path("delete_comment/<int:comment_id>/", views.delete_comment, name="delete_comment"),
    path("delete_reply/<int:reply_id>/", views.delete_reply, name="delete_reply"),
    path('toggle_like/<int:post_id>/', views.toggle_like, name='toggle_like'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('edit_comment/', views.edit_comment, name='edit_comment'),
]

accounts/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pics/', default='default.png')
    date_of_birth = models.DateField(null=True, blank=True)
    confirmation_token = models.UUIDField(default=uuid.uuid4, editable=False)
    confirmation_sent_at = models.DateTimeField(default=timezone.now)

    def confirmation_token_expired(self):
        expiration_time = timezone.now() - timedelta(days=1)  # 1 día de validez, ajusta según necesites
        return self.confirmation_sent_at < expiration_time

    def __str__(self):
        return f'{self.user.username} Profile'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile
from django.core.exceptions import ValidationError
import datetime

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def clean_email(self):
        # Obtén el correo electrónico proporcionado en el formulario
        email = self.cleaned_data['email']

        # Verifica si ya existe un usuario con ese correo electrónico
        if User.objects.filter(email=email).exists():
            raise ValidationError("Ya existe un usuario con ese correo electrónico.")

        return email


class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(required=True, error_messages={'required': 'El campo first name es obligatorio.'})
    last_name = forms.CharField(required=True, error_messages={'required': 'El campo last name es obligatorio.'})


    date_of_birth = forms.DateField(
        widget=forms.DateInput
        (attrs={
            'type': 'date',
            'min': '1940-01-01',
            'max': '2005-12-31'
            }
        )
    )

    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'date_of_birth']

accounts/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, TemplateView
from .forms import RegisterForm, UserProfileForm
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from .models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.views import LoginView as AuthLoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives

class CustomLoginView(AuthLoginView):
    def form_valid(self, form):
        # Llama al comportamiento original de form_valid
        response = super().form_valid(form)
        
        # Verifica si el usuario seleccionó "login_as_admin"
        login_as_admin = self.request.POST.get('login_as_admin', False)

        if login_as_admin:
            if self.request.user.is_staff:  # verifica si el usuario tiene permisos de administrador
                return redirect(reverse('admin:index'))  # Redirige a la consola de administración
            else:
                # Si no tiene permisos de administrador
                messages.error(self.request, "No puedes iniciar sesión como administrador.")
                return redirect(reverse('login'))
        return response

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False  # No activar el usuario hasta que confirme el correo
        user.save()
        profile = UserProfile.objects.create(user=user)

        # Enviar correo electrónico de confirmación
        confirmation_link = self.request.build_absolute_uri(
            reverse('confirm_email', args=[profile.confirmation_token])
        )
        subject = 'Confirmación de Registro'
        from_email = settings.DEFAULT_FROM_EMAIL
        to = user.email
        text_content = 'Por favor, confirma tu registro haciendo clic en el siguiente enlace.'
        html_content = render_to_string('accounts/confirmation_email.html', {
            'confirmation_link': confirmation_link
        })

        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        return super(RegisterView, self).form_valid(form)

def confirm_email(request, token):
    try:
        profile = UserProfile.objects.get(confirmation_token=token)
        if profile.confirmation_token_expired():
            context = {'message': 'El enlace de confirmación ha expirado.'}
            return render(request, 'accounts/email_confirmation.html', context)
        else:
            profile.user.is_active = True
            profile.user.save()
            context = {'message': 'Tu correo electrónico ha sido confirmado exitosamente.'}
            return render(request, 'accounts/email_confirmation.html', context)
    except UserProfile.DoesNotExist:
        context = {'message': 'Enlace de confirmación inválido.'}
        return render(request, 'accounts/email_confirmation.html', context)
    
class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Si se proporciona user_id, muestra el perfil de ese usuario
        user_id = self.kwargs.get('user_id')
        if user_id:
            context['profile_user'] = get_object_or_404(User, id=user_id)
        else:
            # De lo contrario, muestra el perfil del usuario autenticado
            context['profile_user'] = self.request.user
            
        # En el contexto de su vista de perfil
        context['password_reset_url'] = reverse('password_reset', kwargs={'from_where': 'profile'})

        return context
    
# @login_required
# def update_profile(request):
#     profile, created = UserProfile.objects.get_or_create(user=request.user)
    
#     if request.method == 'POST':
#         form = UserProfileForm(request.POST, request.FILES, instance=profile)
#         if form.is_valid():
#             form.save()
#             request.user.first_name = request.POST['first_name']
#             request.user.last_name = request.POST['last_name']
            

#             # Verificar si los campos first_name y last_name están en blanco
#             if not request.user.first_name or not request.user.last_name:
#                 messages.error(request, "Los campos de 'first name' y 'last name' son obligatorios.")
#                 return redirect('update_profile')


#             request.user.save()
#             return redirect('profile')
#     else:
#         # Si el perfil ya tiene una fecha de nacimiento, omite el campo en el formulario
#         if profile.date_of_birth:
#             initial_data = {
#                 'profile_picture': profile.profile_picture,
#                 'date_of_birth': profile.date_of_birth
#             }
#             form = UserProfileForm(instance=profile, initial=initial_data)
#         else:
#             form = UserProfileForm(instance=profile)

#     return render(request, 'accounts/update_profile.html', {'form': form})



@login_required
def update_profile(request):
    profile, created = UserProfile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            # Obtener los datos del formulario
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')

            # Verificar si los campos first_name y last_name están en blanco
            if not first_name or not last_name:
                messages.error(request, "Los campos de 'first name' y 'last name' son obligatorios.")
                return render(request, 'accounts/update_profile.html', {'form': form})

            # Guardar el perfil y el usuario
            form.save()
            request.user.first_name = first_name
            request.user.last_name = last_name
            request.user.save()

            messages.success(request, "Perfil actualizado con éxito.")
            return redirect('profile')
        else:
            # Si el formulario no es válido, muestra los errores
            messages.error(request, "Hay errores en el formulario.")
    else:
        form = UserProfileForm(instance=profile)

    return render(request, 'accounts/update_profile.html', {'form': form})











# En la vista de restablecimiento de contraseña
class CustomPasswordResetView(PasswordResetView):
    template_name = "accounts/registration/password_reset_form.html"
    email_template_name = "accounts/registration/password_reset_email.html"
    subject_template_name = "accounts/registration/password_reset_subject.txt"

    def dispatch(self, *args, **kwargs):
        from_where_url = self.kwargs.get('from_where', None)
        
        if from_where_url in ['profile', 'login']:
            # Si viene de 'profile' o 'login', toma 'from_where' de la URL
            self.request.session['from_where'] = from_where_url
        else:
            # En otros casos, toma 'from_where' de la variable de sesión
            from_where_session = self.request.session.get('from_where', 'login')
            self.request.session['from_where'] = from_where_session
            
        return super().dispatch(*args, **kwargs)


# En la vista que maneja la finalización del restablecimiento de la contraseña
def password_reset_complete_view(request):
    if 'from_where' in request.session:
        del request.session['from_where']
    # Aquí puede redirigir al usuario o mostrar una plantilla, según lo necesite
    return redirect('login')  # Redirigir al inicio de sesión como ejemplo

accounts/templates/accounts/confirmation_email.html
<!DOCTYPE html>
<html>
<head>
    <title>Confirmación de Registro</title>
</head>
<body>
    <p>Gracias por registrarte. Haz clic en el enlace de abajo para confirmar tu registro:</p>
    <a href="{{ confirmation_link }}">Confirmar Registro</a>
</body>
</html>

accounts/templates/accounts/email_confirmation.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Confirmación de Registro</title>
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
        <style>
            h1,p {
                color: #ffffff;
                text-align: center;
            }
        </style>
</head>

<body>
    <main>
        <div class="limiter">
            <div class="container-login100" style="background-image: url('/static/img/bg-01.jpg');">
                <div class="wrap-login100">
                    <h1>Confirmación de Correo Electrónico</h1> <br>
                    <p>{{ message }}</p> <br>
                    {% if message == 'Tu correo electrónico ha sido confirmado exitosamente.' %}
                        <a href="{% url 'login' %}" class="login100-form-btn">Iniciar Sesión</a>
                    {% else %}
                        <a href="{% url 'home' %}" class="login100-form-btn">Volver al Inicio</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </main>
</body>

</html>

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}NeivaNet{% endblock %}</title>

     <!-- Agrega los estilos de Bootstrap y Font Awesome -->
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
 
     <!-- Enlaza tu archivo de estilos personalizado -->
     <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>

  <body>
    <main>
      <div class="limiter">
        <div
          class="container-login100"
          style="background-image: url('/static/img/bg-01.jpg')"
        >
          <div class="wrap-login100">
            <form method="post" class="login100-form validate-form">
              {% csrf_token %}

              <span class="login100-form-logo">
                <i class="fa-solid fa-ethernet icon"></i>
              </span>

              <span class="login100-form-title"> Login </span>

              <div class="form-group">
                {{ form.username.label_tag }}
                <input type="text" name="username" maxlength="30" />
              </div>

              <div class="form-group">
                {{ form.password.label_tag }}
                <input type="password" name="password" maxlength="50" />
              </div>

              <div class="form-group form-group-row">
                <input
                  type="checkbox"
                  name="login_as_admin"
                  id="login_as_admin"
                />
                <label for="login_as_admin"
                  >Iniciar sesión como administrador</label
                >
              </div>

              {% if form.errors or messages %}
              <div>
                {% for error in form.non_field_errors %}
                    <p class="error-message">{{ error }}</p>
                {% endfor %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <p class="error-message">{{ error }}</p>
                    {% endfor %}
                {% endfor %} 
                {% for message in messages %}
                    <p class="error-message">{{ message }}</p>
                {% endfor %}
              </div>
              {% endif %}

              <div class="container-login100-form-btn">
                <button
                  type="submit"
                  class="login100-form-btn"
                  id="loginButton"
                >
                  Login
                </button>
              </div>
            </form>

            <div id="modal" class="modal" style="display: none">
              <div class="modal-content">
                <h2>En un momento podrás ver la ventana principal</h2>
              </div>
            </div>

            <div class="form-footer">
              <a href="{% url 'register' %}"
                >Don't have an account? Register here</a
              >
            </div>
            <div class="form-footer">
              <a href=" {% url 'password_reset' 'login' %} "
                >Forgot Password?</a
              >
            </div>
          </div>
        </div>
      </div>
    </main>
    <script>
        var modal = document.getElementById("modal");

        document.getElementById('loginButton').addEventListener('click', function() {
            modal.style.display = "block";
        });
        
    </script>
  </body>
</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="right_row">
  <div class="profile-info">
    <h2 class="profile-title">{{ profile_user.username }}</h2>
    {% if profile_user.userprofile and profile_user.userprofile.profile_picture and profile_user.userprofile.profile_picture.url != 'default.png' %}
      <img src="{{ profile_user.userprofile.profile_picture.url }}" onerror="this.onerror=null;this.src='{% static 'default.png' %}';" alt="{{ profile_user.username }}" width="200">
    {% else %}
      <img src="{% static 'default.png' %}" alt="Default Profile Pic" width="200">
    {% endif %}
    <p><strong>Nombre de usuario:</strong> {{ profile_user.username }}</p>
    <p><strong>Correo electrónico:</strong> {{ profile_user.email }}</p>
    <p><strong>Nombres:</strong> {{ profile_user.first_name }}</p>
    <p><strong>Apellidos:</strong> {{ profile_user.last_name }}</p>
    <p><strong>Fecha de nacimiento:</strong> {{ profile_user.userprofile.date_of_birth }}</p>
    {% if request.user == profile_user %}
      <div class="form-footer" style="margin-top: 30px;">
        <a class="ancla_button" href="{% url 'update_profile' %}">Actualizar perfil</a>
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}NeivaNet{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css'%}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    
</head>

<body>
  <main>
    <div class="limiter">
      <div class="container-login100" style="background-image: url('/static/img/bg-01.jpg');">
        <div class="wrap-login100">

          <form method="post" id="registerForm" class="register-form">
            {% csrf_token %}

            <span class="login100-form-logo">
              <i class="fa-solid fa-ethernet icon"></i>
            </span>

            <span class="login100-form-title">
              Register
            </span>

            <div class="form-group">
              {{ form.username.label_tag }} <input type="text" name="username" maxlength="30">
            </div>

            <div class="form-group">
              {{ form.email.label_tag }} <input type="email" name="email" maxlength="100">
            </div>

            <div class="form-group">
              {{ form.password1.label_tag }} <input type="password" name="password1" maxlength="50">
            </div>

            <div class="form-group">
              {{ form.password2.label_tag }} <input type="password" name="password2" maxlength="50">
            </div>

            {% if form.errors %}
            <p>{{ form.errors }}</p>
            {% endif %}

            <div class="container-login100-form-btn">
              <button type="submit" class="login100-form-btn" id="registerButton">
                Register
              </button>
            </div>

          </form>
          <div class="form-footer">
            <a href="{% url 'login' %}">Already have an account? Login here</a>
          </div>
        </div>
      </div>
    </div>
  </main>
  <!-- Modal de Confirmación -->
  <div id="modal" class="modal" style="display: none">
    <div class="modal-content">
        <h2>Por favor, revisa tu correo para confirmar tu registro.</h2>
    </div>
</div>

<script>
    var modal = document.getElementById("modal");
    var registerButton = document.getElementById('registerButton');

    registerButton.addEventListener('click', function(event) {
        modal.style.display = "block";
        setTimeout(function() {
            window.location.href = "{% url 'login' %}";
        }, 5000); // Redirige después de 5 segundos
    });
</script>
</body>

</html>

accounts/templates/accounts/update_profile.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="right_row">

  <div class="row border-radius">
    <div class="feed">
        <div class="feed_title">
          <form method="post" class="register-form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group form-index">
              <br />
              <label for="id_profile_picture">Profile picture:</label>
              <br />
              
              {% if user.userprofile and user.userprofile.profile_picture and user.userprofile.profile_picture.url != 'default.png' %}
              <img
                src="{{ user.userprofile.profile_picture.url }}"
                alt="Current Profile Pic"
                width="50"
              />
              {% else %}
              <img
                src="{% static 'default.png' %}"
                alt="Default Profile Pic"
                width="50"
              />
              {% endif %}
              <br />
              Change:
              <input type="file" name="profile_picture" id="id_profile_picture" />
            </div>
          
            <!-- Add first_name and last_name fields -->
             <!-- Campo first_name -->
             <div class="form-group form-index">
              <label for="id_first_name">First Name: <span class="text-danger">*</span></label>
              <input
                type="text"
                name="first_name"
                id="id_first_name"
                value="{{ user.first_name }}"
                maxlength="20"
                required  
              />
            </div>

            <!-- Campo last_name -->
            <div class="form-group form-index">
              <label for="id_last_name">Last Name: <span class="text-danger">*</span></label>
              <input
                type="text"
                name="last_name"
                id="id_last_name"
                value="{{ user.last_name }}"
                maxlength="20"
                required  
              />
            </div>
<!-- Campo date_of_birth -->
<div class="form-group form-index">
  {{ form.date_of_birth.label_tag }} {{ form.date_of_birth }}
  {% if form.date_of_birth.errors %}
      <div class="alert alert-danger">
          {{ form.date_of_birth.errors }}
      </div>
  {% endif %}
</div>


            {% if form.errors %}
            <ul class="errorlist">
              {% for error in form.errors %}
              <li>{{ error|escape }}</li>
              {% endfor %}
            </ul>
            {% endif %}

            <div class="publish_icons" style="border: none;">
              <button type="submit" style="margin: 0 auto;">Update</button>
              <button style="text-align: center; margin: 0 auto;"><a href="{% url 'profile' %}"></a>Cancel</button>
            </div>

            <div>
              <a href="{% url 'password_reset' 'profile' %}" class="update-password-button">Change Password</a>
            </div>
            
          </form>
        </div>
    </div>
</div>
</div>

{% endblock %}